apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: '*'
  newName: quay.io/waynecabanto/next-sample-app
commonAnnotations:
  app.openshift.io/vcs-ref: 9d2e637f1eb7ce8b34134e90f7e3140ab8186a88
  app.openshift.io/vcs-uri: https://github.com/waynecabanto/next-sample-app
