apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: '*'
  newName: quay.io/waynecabanto/express-sample-app
  newTag: 8f579a00c14814e6f4d4a9172f404ef41b095610
commonAnnotations:
  app.openshift.io/vcs-ref: 8f579a00c14814e6f4d4a9172f404ef41b095610
  app.openshift.io/vcs-uri: https://github.com/waynecabanto/express-sample-app
